Repository ayuushhh/Frontend-Mentor-Social-proof-section, pull requests merged in 2021-10, with the labels that each got.

#5 Update styles.css
  css/styles.css
Labels: hacktoberfest, hacktoberest-accepted

#6 Update index.html
  index.html
Labels: hacktoberest-accepted

#7 Changed the position of the heading
  README.md
Labels: hacktoberest-accepted

#9 Changed index.html
  index.html
Labels: hacktoberfest-accepted

#12 Changed index.html
  index.html
Labels: hacktoberfest-accepted

#11 Changed styles.css
  styles.css
Labels: hacktoberfest-accepted

#10 Changed styles.css
  styles.css
Labels: hacktoberfest-accepted

#14 updated styles.css
  styles.css
Labels: hacktoberfest-accepted

#13 Updated padding in buyers section
  styles.css
Labels: hacktoberfest-accepted
